name: .NET Core

on:
  push:
    branches: [ master ]

jobs:
  build:

   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v2
   - name: Setup .NET Core
     uses: actions/setup-dotnet@v1.8.0
     with:
       dotnet-version: 5.0.6
   - name: Install dependencies
     run: dotnet restore ~\Leatherback.Package.sln
   - name: Build
     run: dotnet build --configuration Release --no-restore ~\Leatherback.Package.sln
     
#    - name:Test
#    run: dotnet test --no-restore --verbosity normal
