name: .NET Core

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore Leatherback.Package.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore Leatherback.Package.sln --version-suffix 'dev-${{ steps.date.outputs.date }}'
    - name: Test
      run: dotnet test --no-restore --verbosity normal Leatherback.Package.sln    
    - name: Pack NuGet
      run: dotnet pack Leatherback.Package.sln --version-suffix 'dev-${{ steps.date.outputs.date }}'
    - name: Publish NuGet
      run: dotnet nuget push **/*.nupkg  -k ${{ secrets.NUGETAPIKEY }} --skip-duplicate -s https://api.nuget.org/v3/index.json   
